# Generated by Django 5.1.3 on 2024-12-05 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock",
            name="total_buying_cost",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="stock",
            name="total_selling_cost",
            field=models.FloatField(default=0.0),
        ),
    ]
