# Generated by Django 5.1.3 on 2024-12-07 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0002_alter_purchase_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="bill",
            name="discount",
            field=models.IntegerField(default=0),
        ),
    ]
