# Generated by Django 5.0.6 on 2024-11-28 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0002_stock_total_purchased_stock_total_sold_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchase",
            name="product",
            field=models.CharField(max_length=255),
        ),
    ]
