# Generated by Django 5.1.3 on 2024-12-05 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0002_alter_stock_total_buying_cost_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billitemproduct",
            name="rate",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
