# Generated by Django 5.0.6 on 2024-12-03 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0002_bill_customer_billitem_bill_customer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="billitem",
            name="products",
        ),
        migrations.RemoveField(
            model_name="billitem",
            name="quantity",
        ),
        migrations.CreateModel(
            name="BillItemProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("rate", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "bill_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="stock.billitem",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="stock.product"
                    ),
                ),
            ],
        ),
    ]
