# Generated by Django 5.1.3 on 2024-12-08 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0003_bill_discount"),
    ]

    operations = [
        migrations.AddField(
            model_name="bill",
            name="total_amount",
            field=models.FloatField(default=0.0),
        ),
    ]
