# Generated by Django 5.1.3 on 2024-12-05 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0003_alter_billitemproduct_rate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sale",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
