# Generated by Django 5.1.3 on 2024-12-11 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0004_bill_total_amount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="product_code",
        ),
        migrations.AddField(
            model_name="customer",
            name="pan_no",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="SH_code",
            field=models.CharField(default=" ", max_length=50),
        ),
    ]
