# Generated by Django 5.1.3 on 2024-12-12 04:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0005_remove_product_product_code_customer_pan_no_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bill",
            name="payment_type",
            field=models.CharField(
                choices=[("CASH", "Cash"), ("CREDIT", "Credit")],
                default="CASH",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="BillOnCash",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.FloatField(default=0.0)),
                ("date", models.DateField(default=django.utils.timezone.now)),
                (
                    "particulars",
                    models.CharField(default=" ", editable=False, max_length=255),
                ),
                (
                    "bill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="stock.bill"
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="stock.customer"
                    ),
                ),
            ],
        ),
    ]
