# Generated by Django 5.1.3 on 2024-12-12 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0006_bill_payment_type_billoncash"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="SH_code",
            field=models.CharField(default="CV ", max_length=50),
        ),
    ]
