# Generated by Django 5.1.3 on 2024-12-13 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0007_alter_product_sh_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="SH_code",
            field=models.CharField(default="", max_length=50),
        ),
    ]
