# Generated by Django 5.1.3 on 2024-12-13 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0008_alter_product_sh_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="Suppliers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("phone_number", models.CharField(max_length=10)),
                ("pan", models.CharField(max_length=20)),
                ("address", models.CharField(max_length=255)),
            ],
        ),
    ]
