# Generated by Django 5.1.3 on 2024-12-13 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0009_suppliers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="SH_code",
        ),
        migrations.AddField(
            model_name="product",
            name="HS_code",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_no", models.PositiveIntegerField(unique=True)),
                ("date", models.DateField()),
                ("total_amount", models.FloatField(default=0.0)),
                (
                    "payment_type",
                    models.CharField(
                        choices=[("CASH", "Cash"), ("CREDIT", "Credit")],
                        default="CASH",
                        max_length=10,
                    ),
                ),
                (
                    "suppliers",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stock.suppliers",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total", models.FloatField(default=0.0)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="stock.order"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderItemProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "rate",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "order_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="stock.orderitem",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="stock.product"
                    ),
                ),
            ],
        ),
    ]
